---
version:
  - 0
  - 22
  - 0
migrations:
  adopted_cache: true
  fixed_spanish_config: true
manifests:
  "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml":
    etag: "W/\"246274ba0147133a6cc80023a8e90e002ad40104489b71b2e936ba16044cf945\""
    checked: "2024-01-04T04:58:56.396026577Z"
    updated: "2024-01-04T04:58:56.396026577Z"
roots:
  - path: /home/niscolas/.config/heroic
    store: heroic
  - path: /home/niscolas/.config/lutris
    store: other
  - path: /home/niscolas/.local/share/Steam
    store: steam
  - path: /home/niscolas/.var/app/com.heroicgameslauncher.hgl/config/heroic
    store: heroic
  - path: /home/niscolas/.var/app/com.valvesoftware.Steam/.local/share/Steam
    store: steam
  - path: /run/media/niscolas/linux_storage/SteamLibrary
    store: steam
backup:
  recent_games:
    - Apex Legends
    - Barotrauma
    - Blasphemous
    - Borderlands 3
    - Bread & Fred
    - Caveblazers
    - Crawl
    - Crypt of the NecroDancer
    - Darkest Dungeon
    - Deep Rock Galactic
    - Devil May Cry 5
    - Disco Elysium
    - Dishonored 2
    - "Don't Starve Together"
    - Elden Ring
    - En Garde!
    - Enter the Gungeon
    - Full Metal Furies
    - "Guns, Gore & Cannoli 2"
    - Hades
    - Heave Ho
    - Helldivers
    - Hollow Knight
    - Killer Instinct
    - Lone Fungus
    - "Metal: Hellsinger"
    - "Naraka: Bladepoint"
    - Patch Quest
    - Resident Evil Village
    - Risk of Rain 2
    - Risk of Rain Returns
    - Rocket League
    - Rogue Legacy 2
    - Rounds
    - "Sekiro: Shadows Die Twice"
    - Sifu
    - "Stick Fight: The Game"
    - Streets of Rogue
    - Sundered
    - Super Cane Magic ZERO
    - The Finals
    - "Tiny Tina's Wonderlands"
    - Titan Souls
    - Tribes of Midgard
    - Vagante
    - Voidigo
    - Wand Wars
    - Wizard of Legend
restore:
  recent_games:
    - Apex Legends
    - Barotrauma
    - Blasphemous
    - Bloons TD 6
    - Borderlands 3
    - "Borderlands: The Pre-Sequel"
    - Bread & Fred
    - Caveblazers
    - Crawl
    - Crypt of the NecroDancer
    - Darkest Dungeon
    - Deep Rock Galactic
    - Devil May Cry 5
    - Disco Elysium
    - Dishonored 2
    - "Don't Starve Together"
    - Doom (2016)
    - Elden Ring
    - En Garde!
    - Enter the Gungeon
    - Full Metal Furies
    - "Guns, Gore & Cannoli 2"
    - Hades
    - Heave Ho
    - Helldivers
    - Hollow Knight
    - Killer Instinct
    - Lone Fungus
    - "Naraka: Bladepoint"
    - Resident Evil Village
    - Risk of Rain 2
    - Rocket League
    - Rogue Legacy 2
    - "Sekiro: Shadows Die Twice"
    - Shadow of War
    - Sifu
    - "Stick Fight: The Game"
    - Streets of Rogue
    - Sundered
    - Super Cane Magic ZERO
    - "The Witcher 3: Wild Hunt"
    - "Tiny Tina's Wonderlands"
    - Tribes of Midgard
    - Vagante
    - Voidigo
    - Wizard of Legend
