---
runtime:
  threads: ~
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
language: en-US
theme: dark
roots:
  - path: /home/niscolas/.local/share/Steam
    store: steam
  - path: /home/niscolas/.var/app/com.valvesoftware.Steam/.local/share/Steam
    store: steam
  - path: /home/niscolas/.config/heroic
    store: heroic
  - path: /home/niscolas/.config/lutris
    store: lutris
  - path: /mnt/storage/SteamLibrary
    store: steam
  - path: /home/niscolas/.local/share/Steam/steamapps/compatdata/3858932643/pfx/drive_c
    store: gog
redirects: []
backup:
  path: /home/niscolas/bonfire/saves-ludusavi2
  ignoredGames:
    - Apex Legends
    - "BPM: Bullets per Minute"
    - Barotrauma
    - Blasphemous
    - Bloons TD 6
    - Borderlands 3
    - "Borderlands: The Pre-Sequel"
    - Bread & Fred
    - Caveblazers
    - Crawl
    - Crypt of the NecroDancer
    - Darkest Dungeon
    - Deep Rock Galactic
    - Devil May Cry 5
    - Disco Elysium
    - Dishonored 2
    - "Don't Starve Together"
    - Doom (2016)
    - ELDEN RING (Custom All Saves)
    - En Garde!
    - Enter the Gungeon
    - Full Metal Furies
    - Ghostrunner
    - "Guns, Gore & Cannoli 2"
    - Hades
    - Heave Ho
    - Helldivers
    - Hollow Knight
    - Killer Instinct
    - Lethal League Blaze
    - Lone Fungus
    - "Metal: Hellsinger"
    - "Naraka: Bladepoint"
    - Patch Quest
    - Resident Evil Village
    - Risk of Rain 2
    - Risk of Rain Returns
    - Rocket League
    - Rogue Legacy 2
    - Rounds
    - "Sekiro: Shadows Die Twice"
    - Shadow of War
    - Sifu
    - "Stick Fight: The Game"
    - Streets of Rogue
    - Sundered
    - Super Cane Magic ZERO
    - The Finals
    - "The Witcher 3: Wild Hunt"
    - "Tiny Tina's Wonderlands"
    - Titan Souls
    - Tribes of Midgard
    - Ultrakill
    - Vagante
    - Voidigo
    - Wand Wars
    - Wizard of Legend
  filter:
    excludeStoreScreenshots: false
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: name
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: simple
    zip:
      compression: deflate
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
restore:
  path: /home/niscolas/bonfire/saves-ludusavi2
  ignoredGames: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
scan:
  showDeselectedGames: true
  showUnchangedGames: true
  showUnscannedGames: true
cloud:
  remote:
    GoogleDrive:
      id: ludusavi-1697211189
  path: my_game_my_rules/saves-ludusavi
  synchronize: true
apps:
  rclone:
    path: rclone
    arguments: ""
customGames:
  - name: Shadow of War
    files:
      - /home/niscolas/.local/share/Steam/steamapps/compatdata/3858932643/pfx/drive_c/users/steamuser/AppData/Local/WB Games/Shadow of War
    registry: []
  - name: Elden Ring
    files:
      - /mnt/storage/SteamLibrary/steamapps/compatdata/1245620/pfx/drive_c/users/steamuser/AppData/Roaming/EldenRing
    registry: []
  - name: OTXO
    files:
      - /mnt/storage/SteamLibrary/steamapps/compatdata/1608640/pfx/drive_c/users/steamuser/AppData/Local/OTXO_Release
    registry: []
