"$schema" = 'https://starship.rs/config-schema.json'

format = """
[$os](neutral_blue bold)[](neutral_blue)[$username $hostname](fg:dark_soft bg:neutral_blue bold bold)[](neutral_blue) \
$directory\
[](yellow)[ $git_branch$git_status](fg:dark_soft bg:yellow bold bold)[](yellow) \
[$all](fg:purple bold)$cmd_duration\
\n$character
"""

palette = "gruvbox"

[palettes.gruvbox]
dark_soft = "#32302F"
light_soft = "#F2E5BC"
red = "#FB4934"
green = "#B8BB26"
yellow = "#FABD2F"
blue = "#83A598"
purple = "#D3869B"
aqua = "#8EC07C"
orange = "#FE8019"
neutral_red = "#CC241D"
neutral_green = "#98971A"
neutral_yellow = "#D79921"
neutral_blue = "#458588"
neutral_purple = "#B16286"
neutral_aqua = "#689D6A"
neutral_orange = "#D65D0E"
faded_red = "#9D0006"
faded_green = "#79740E"
faded_yellow = "#B57614"
faded_blue = "#076678"
faded_purple = "#8F3F71"
faded_aqua = "#427B58"
faded_orange = "#AF3A03"

[character]
success_symbol = "[](green bold)"
error_symbol = "[](red bold)"

[cmd_duration]
min_time = 500
format = "[](green)[ $duration](fg:dark_soft bg:green bold)[](green)"

[directory]
format = "[](aqua)[ $path](fg:dark_soft bg:aqua bold)[](aqua) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "$symbol$branch(:$remote_branch)"
symbol = ""

[git_status]
format = "$all_status$ahead_behind"
conflicted = " 󱓌"
ahead = " "
behind = " "
diverged = " 󰦾"
up_to_date = " "
untracked = " 󰨹"
stashed = " 󰀼"
modified = " 󰷈"
staged = " "
renamed = " 󰑕"
deleted = " 󰚃"

[line_break]
disabled = true

[lua]
format = "$symbol $version"
symbol = ""

[nodejs]
symbol = " "
format = "$symbol$version "

[os]
format = "$symbol"
disabled = false

[os.symbols]
Arch = ""

[package]
format = "$symbol$version "
symbol = "󰏗 "

[rust]
format = "$symbol$version "
symbol = " "

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "fg:dark_soft bg:green bold"
format = "[](green)[ $time]($style)[](green)"

[username]
show_always = true
format = " $user"

[hostname]
ssh_only = false
ssh_symbol="󰢹"
format = "󰒋 $ssh_symbol $hostname"
