import:
  - ~/.config/alacritty/themes/gruvbox_dark.yml

window:
  option_as_alt: Both

  dimensions:
    columns: 84
    lines: 22

  padding:
    x: 0
    y: 0

  decorations: Full
  dynamic_title: true

  history: 10000
  multiplier: 3

  opacity: 0.85

cursor:
  style:
    shape: Block
    blinking: On

  unfocused_hollow: false

live_config_reload: true

key_bindings:
  - { key: F11, action: ToggleFullscreen }
  - { key: Space, mods: Control, chars: "\x00" }

